baseURL = '/'
languageCode = 'en-us'
theme = "nightfall_ip"
favicon = true

[menu]
  [[menu.header]]
    name = "portfolio"
    weight = 0
    url = "portfiolio"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "iiro"
hostname = "puro.la"
  [params.author]
    name = "Iiro Purola"  # Website and RSS feed author
    description = "an Cloud engineer at Cloud2 Oy."
    freetext = "I thrive in the cloud computing landscape, driven by a deep passion for innovative cloud technologies and solutions."
    email = "email@example.com"  # RSS feed email address


readingTime = true  # Show reading time on post page
published = false  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/IiroPurola"
icon = "fa-brands fa-github"

[[params.social]]
key = 1
name = "instagram"
url = "https://www.instagram.com/iiro.purola/"
icon = "fa-brands fa-instagram"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/iiropurola/"
icon = "fa-brands fa-linkedin"

[[params.social]]
key = 3
name = "email"
url = "mailto:iiro@puro.la"
icon = "fa-solid fa-envelope"
